### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kyokomi** [kyokomi/dungeon-api#1]
- [x] 何層で中断するか指定するようAPI改修 https://github.com/kyokomi/dungeon-api/pull/2
- [x] ダンジョン一覧を返すAPI追加 https://github.com/kyokomi/dungeon-api/pull/3
- [x] 探索IDで過去の結果を返すGET API追加 https://github.com/kyokomi/dungeon-api/pull/4
- [x] ステータス取得と反映のAPI追加
