### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by kyokomi** [kyokomi/dungeon-api#9]
#### Main

- [x] ダンジョンを探索する
- [x] プレイヤーのパラメータ振り分けをする
- [ ] プレイヤーの装備を変更する
- [ ] プレイヤーの所持品を倉庫に預ける・引き出す
- [ ] アイテムを購入・売却する
- [ ] クエスト受注・精算する

#### MEMO

- [x] 探索のイベント抽選で敵と遭遇する
- [ ] 敵と遭遇した瞬間は、先制攻撃、待機、不意打ちのいずれかが抽選される
    - 先制攻撃: 遭遇と同時にプレイヤーが戦闘行動が行える
    - 待機: プレイヤーも敵も行動しない
    - 不意打ち: 遭遇と同時に敵が戦闘行動を行える
- [x] 敵と遭遇中はイベント抽選されず戦闘行動が抽選される
    - 戦闘行動: 攻撃、スキル発動、アイテム使用（ステータスやHP/MPの状況、所持アイテム、性格によって行動はランダム）
- [ ] プレイヤーにはさまざまな性格があり、性格によってイベント抽選前の行動判定が多少異なる
- [x] プレイヤーが所持できるアイテム数の制限があり、持ちきれない場合アイテムを捨てる
- [ ] プレイヤーは武器や防具を１つづつ装備することができる
- [x] プレイヤーはフロア到達すると経験値獲得する
- [x] プレイヤーは敵を撃破すると経験値獲得する
- [x] プレイヤーは経験値を消費してステータスを上げることができる
- [x] プレイヤーはイベント毎にMPを消費する
- [ ] プレイヤーはスキルの習得とスキル発動が行える
- [x] 最下層に到達したらダンジョンのクリアとして脱出する
- [x] ダンジョン毎に1回の行動を行う時間が異なる（1回の行動に5分/10分などかかる）
- [x] 探索開始時に指定した階に到達したら中断として脱出する
- [x] 時間ではなく行動回数で次のフロアへ移動する（アイテム使用とかは行動回数と認めない）
- [ ] チャレンジクエストみたいな（ゴブリンを10体撃破する等）ものを入れる
- [ ] プレイ中に次の行動で装備変更を選択できる（1探索での回数制限あり）
- [ ] プレイ中に次の行動でアイテム消費を選択できる（1探索での回数制限あり）
- [ ] 探索に失敗（プレイヤーが倒れる）するとLPが減り、0になると死亡してそのプレイヤーで冒険できなくなる
- [ ] 1アカウントで複数プレイヤーを扱うことができる（課金or死亡）
- [ ] 1アカウントで倉庫は1つ
- [ ] 倉庫に預けられるアイテムの数は決まっているが拡張可能（課金）

**Comment by kyokomi** [comment]
ソースコード上のTODOを追加

- [ ] explorationにenemyを直接持たせるのをやめる（enemyIDだけ持たせて別テーブルとか）
- [ ] updateStatusのトランザクション考慮できてない件をなんとかする
- [ ] マスタデータをどうするか？（バケット？ -> MemCache？）
    - [ ] アイテム
    - [ ] モンスター
    - [ ] ダンジョン
- [ ] 罠が足りない
- [ ] 敵が足りない
- [ ] アイテムが足りない
- [ ] 装備がない
- [ ] スキルがない

**Comment by kyokomi** [comment]
Backlog持って行ってないやつ

-  プレイ中に次の行動で装備変更を選択できる（1探索での回数制限あり）
-  プレイ中に次の行動でアイテム消費を選択できる（1探索での回数制限あり）
-  探索に失敗（プレイヤーが倒れる）するとLPが減り、0になると死亡してそのプレイヤーで冒険できなくなる
-  1アカウントで複数プレイヤーを扱うことができる（課金or死亡）
-  1アカウントで倉庫は1つ
-  倉庫に預けられるアイテムの数は決まっているが拡張可能（課金）

**Comment by kyokomi** [comment]
issue別で切ったのでClose
